### ISSUE TITLE
Unit Tests and source

### ISSUE THREAD

**Issue by AlinGab** [AlinGab/Quiz-final-project-#1]
Create unit tests for the following areas:

CRUD: Test all CRUD functions (create, read, update, delete) for User, Question, and Game.

SCHEMAS: Validate schema definitions using Pydantic models for users, questions, and games.

MODELS: Test relationships between models (User → Game, Game → Question).

DATABASE: Ensure that the test database (test_quiz_game.db) is properly initialized and that the tables (ex users, questions, game) are correctly created.

EXTRA:

Verify for any incorrect behaviours or missing input and integrate the Database within FASTAPI

**Comment by DacianMocan1337** [comment]
Unit tests processed
